# Generated by Django 4.2 on 2023-04-30 22:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=300, null=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2023, 4, 30, 22, 17, 56, 528483, tzinfo=datetime.timezone.utc), editable=False)),
                ('slug', models.SlugField(default='dummy-wish-list', verbose_name='Slug')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ManyToManyField(to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('link', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='images/wishes/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('description', models.CharField(max_length=500, null=True)),
                ('bought', models.BooleanField(default=False)),
                ('wish_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wishes.wishlist')),
            ],
        ),
    ]
