# Generated by Django 4.2 on 2023-04-30 22:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0002_alter_wishlist_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 30, 22, 24, 38, 133671, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
