# Generated by Django 4.2 on 2023-04-30 23:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0003_alter_wishlist_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wish',
            options={'verbose_name': 'Wish', 'verbose_name_plural': 'Wishes'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'Wish List', 'verbose_name_plural': 'Wish Lists'},
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
