# Generated by Django 4.2 on 2023-05-06 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0004_alter_wish_options_alter_wishlist_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='image',
        ),
        migrations.AlterField(
            model_name='wish',
            name='link',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
