# Generated by Django 4.2 on 2023-06-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wishes", "0008_alter_wish_bought_alter_wish_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wish",
            name="description",
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
    ]
